### ISSUE TITLE
Using a Slider inside the drawer's view

### ISSUE THREAD

**Issue by PierreGUI** [manumaticx/Ti.DrawerLayout#10]
Hey guys,
I'm trying to use a slider in the drawer, unfortunately I can't slide it: it slides the drawer. :(
Here is a small test app: https://gist.github.com/PierreGUI/d47090cce2a5cbada4f7

Hope we can do something about it.
Cheers
Pierre

**Comment by manumaticx** [comment]
Hi @PierreGUI 

I found a workaround. It's quick-and-dirty but it works.

Actually, I would have to tweak the Slider or to be precise the TiViewProxy in the Titanium SDK. But I have added a method to the Drawer Proxy that lets you do the following:

```javascript
var slider = Ti.UI.createSlider({
    width:'90%',
    height:30,
    min:0,
    top:40,
    max:100,
    value:0
});
slider.addEventListener('touchstart', function(){
  drawer.interceptTouchEvent(drawerView, true);
});
slider.addEventListener('touchend', function(){
  drawer.interceptTouchEvent(drawerView, false);
});
drawerView.add( slider );
```

The `interceptTouchEvent` method is available in the 1.2.1 dist that I've just updated. This should solve your issue.

**Comment by PierreGUI** [comment]
Man, you rock :+1: !
Thanks a lot

**Comment by manumaticx** [comment]
You're welcome! Does it work for you? (I've used you test app)

**Comment by PierreGUI** [comment]
YES ! :)
