### ISSUE TITLE
drawer listener no longer firing when set windowActionBar to false in custom theme

### ISSUE THREAD

**Issue by dyan02** [manumaticx/Ti.DrawerLayout#12]
when i try to hide windowActionBar in custom theme,

here is my custom theme
`
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.NoActionBar" parent="@style/Theme.Titanium">
        <item name="windowActionBar">false</item>
    </style>
</resources> 
`

i no longer receive fire event from drawer..
`
 drawer.addEventListener('draweropen', function(e) {
            Ti.API.info('openn');
    	});
    	drawer.addEventListener('drawerclose', function(e) {
            Ti.API.info('close');
    	});
    	drawer.addEventListener('drawerslide', function(e) {
            Ti.API.info('slide');
    	});
`
those will return nothing.

**Comment by manumaticx** [comment]
Thanks for reporting. Fixed! :)
