### ISSUE TITLE
Burger to Arrow animated icon in action bar

### ISSUE THREAD

**Issue by GeraudBourdin** [manumaticx/Ti.DrawerLayout#15]
Hi, 
i wanted to send a private message but we can't, so here i am. 
I was just playing to see if it was possible to add the android L animation icon in the action bar and i ended up with this simple solution with the DrawerArrowDrawable from ChrisRenke.

here is my fork link to the module and test app:
https://github.com/GeraudBourdin/Ti.DrawerLayout/
https://github.com/GeraudBourdin/Ti.DrawerLayout-Demo-Alloy-App

I do not know if this functionnality is usefull and/or if my code is good enough for a pull request so let me know.  :)

**Comment by manumaticx** [comment]
Very cool. Thanks! I'll check it out as soon as possible

**Comment by GeraudBourdin** [comment]
Here is a gif preview i just made.
![Image of arrow animation](http://i.imgur.com/Jg8k2P9.gif?1)

**Comment by nuno** [comment]
Nice!

**Comment by thomasBourdin** [comment]
Nice work ! ^^

**Comment by manumaticx** [comment]
@GeraudBourdin This looks awesome! And it seems to work just fine. Great work! :+1: 

If you send me pull request to the module and the demo app I would like to merge this for now! 

But FYI, I intend to replace this solution as soon as Titanium 4.0.0 is released in April with official Material (AppCompat) support.

**Comment by manumaticx** [comment]
Merged: #16 :)

**Comment by manumaticx** [comment]
@GeraudBourdin I've just fooled around with this one.. Have you tried to change the color of the DrawerArrowDrawable? 

I tried using `drawerArrowDrawable.setStrokeColor()` but it doesn't work for me. It replaces the drawable with the App icon.

**Comment by GeraudBourdin** [comment]
I ll have a look tomorow morning and get back to you quickly :)

**Comment by AhmedTheGeek** [comment]
@manumaticx Do you have any idea why the burger animation doesn't working on v4.0 Ti SDK ?

**Comment by manumaticx** [comment]
@AhmedTheGeek I'm going to test 4.0.0 when it's beta. I'll make the Drawer compatible then.

**Comment by GeraudBourdin** [comment]
@manumaticx : i've just sent a pull request. I am sorry for that, my previous pull was... hem... pretty buggy. Please review my code before merging it, i am new to java and titanium module! :)

@AhmedTheGeek : i've tested the latest 4.* before trying to use other lib (like this one). Have no idea why it's not working, but i've loose my hole weekend trying to use it... :)

**Comment by manumaticx** [comment]
Since this solution replaces the actionbar icon with the arrow drawable, do you have any idea how we could support both, arrow drawable __and__ icon?

**Comment by GeraudBourdin** [comment]
I've just began to work on it.. But i don't know yet if i ll end up with a nice solution. I'll try :)

**Comment by manumaticx** [comment]
I have an idea. Getting back in a second....

**Comment by manumaticx** [comment]
okay, it does work if you replace
```java
activity.getSupportActionBar().setIcon(drawerArrowDrawable);
```
with
```java
activity.getSupportActionBar().setHomeAsUpIndicator(drawerArrowDrawable);
```
(and using `actionBar.displayHomeAsUp = true;`)

but we need to get some left and right padding to the drawable. should be possible, isn't it?

**Comment by GeraudBourdin** [comment]
i don't find how to add padding right and left to the up carret... Is that really possible ? Did you solve that too ? Btw, your activity.getSupportActionBar().setHomeAsUpIndicator(drawerArrowDrawable) works great :+1:

**Comment by manumaticx** [comment]
I'm struggling with the left padding.... I'll commit my current attempt.

**Comment by GeraudBourdin** [comment]
it works great on the right side ! I was wondering if it was possible to set a custom layout for the actionBar ?

**Comment by manumaticx** [comment]
I would not do this from within this module because of two reasons.

1. This module aims to implement the DrawerLayout and should not do anything else (it should reduce its interaction with the ActionBar to a minimum)

2. This feature is not worth such a breaking change. As mentioned above, I'll try to implement the native support for this functionality with the release of Titanium 4.0.0 which will likely replace ChrisRenke's workaround.

I'm sure there is an easy solution for the padding issue. I have to admit that my Java / Android skills aren't that good ;)  ...maybe it's possible to wrap a View around the drawerArrowDrawable, add a left margin there and use this as homeAsUpIndicator. I'm going to give it another try tomorrow.

**Comment by GeraudBourdin** [comment]
Well, that's a point. ^^
I have few things to do today, i'll try on my side too. Let me know if you succeed on it :)

**Comment by GeraudBourdin** [comment]
Got this working, just cleaning up before sending pr. :)

**Comment by manumaticx** [comment]
Wow! Awesome! Didn't had the time yet, looking forward to your fix :)

**Comment by manumaticx** [comment]
Closing this. Again, thank you very much, Geraud! It's just fantastic. (btw: here's another little [gif](https://twitter.com/manumaticx/status/578630611482591232) )

**Comment by GeraudBourdin** [comment]
@manumaticx : sorry for re-opening this thread, but i don't know how to send you pvt message.
First, i am very happy that this burger feature have been added to this project, thanks again for every thing you 've done for it ! :) 
I was just wandering if it would be a good idea to add compatibility with the ios version of the nappdrawer module ?  I would be glad to dig in it, and try to make a full solution to have the best for both android and ios solution. Tell me if it would be a good idea, so i do not waste some time to help with a useless feature :)

**Comment by manumaticx** [comment]
@GeraudBourdin  I have already built an Alloy widget to wrap this module for Android together with [TiSideMenu](https://github.com/mpociot/TiSideMenu) for iOS on the same code base on the analogy of https://github.com/FokkeZB/nl.fokkezb.drawer. I've not open-sourced this widget yet but I think it would be easy add support for NappDrawer. Anyway, this is less work than adding native Drawer support to the NappDrawer module (https://github.com/viezel/NappDrawer/issues/113).

**Comment by GeraudBourdin** [comment]
That would be great i you could make your widget open sourced so i could work on the ios nappdrawer port. (btw my goal was to learn android module developpement). switch my last project to  ti.drawerLayout that allready use the nappdrawer with the fokkeZB project could be fun too. I have time this week, and if it helps the community... :)

**Comment by manumaticx** [comment]
I'm going to to upload the widget later this week

**Comment by manumaticx** [comment]
@GeraudBourdin Sorry, I didn't yet got that widget up here. But look, Fokke Zandbergen added support for this module to his drawer widget: https://github.com/FokkeZB/nl.fokkezb.drawer :)

**Comment by GeraudBourdin** [comment]
Awesome! I'll test it as soon as possible. Thank a lot for the info :)
