### ISSUE TITLE
Can't use "100%" or Ti.UI.FILL for rightDrawerWidth to fully slide the view

### ISSUE THREAD

**Issue by ANR2ME** [manumaticx/Ti.DrawerLayout#22]
Is there any workaround if i want to partially slide left view (ie.menu) and fully slide the right view (ie.next page)? using 'auto' couldn't show the the whole page either

**Comment by manumaticx** [comment]
Yeah, well, currently it is only possible to specify dp values for the width. So the workaround for now would be to use the displayWidth as rightDrawerWidth:

```js
var rightWidth = Ti.Platform.displayCaps.platformWidth / Ti.Platform.displayCaps.logicalDensityFactor;

Alloy.Globals.drawer = TiDrawerLayout.createDrawer({
  leftView : menuView,
  rightView: rightDrawer,
  centerView : contentView,
  leftDrawerWidth : 240,
  rightDrawerWidth : rightWidth
});
```

I'm thinking over how we could drop the `leftDrawerWidth` and `rightDrawerWidth` properties to let the module automatically use the width of the views. That would make it much more simple.

**Comment by ANR2ME** [comment]
Thanks for the code :)
and it would be nice if it can auto-use each view's width like that.
