### ISSUE TITLE
openLeftDrawer not consistently updating burger-to-arrow

### ISSUE THREAD

**Issue by ricardoalcocer** [manumaticx/Ti.DrawerLayout#23]
**I CAN NOT consistently replicate this behavior:**

An app I'm working on calls openLeftDrawer() on window load, to show the menu right away.  When open, the hamburger should be in Arrow state, however, it's still in hamburger state, causing it to morph from hamburger to hamburger.

**Comment by manumaticx** [comment]
I _think_  I can kind of reproduce this. But I do see either no hamburger at all or the correct state .And I believe this is a timing bug...

I've tested this by inserting `Alloy.Globals.drawer.openLeftWindow();` [here](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App/blob/9a9e632b8007aa6fc787d426277ae1d16a9bd5f6/app/controllers/index.js#L117) (right at the end of the onOpen callback) and it works fine there. But if I insert it [here](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App/blob/9a9e632b8007aa6fc787d426277ae1d16a9bd5f6/app/controllers/index.js#L73) (at the beginning of the onOpen callback) it reproduces this behavior.

This "hack" did help too:
```js
// add a small delay before opening the drawer
setTimeout(function(){
  Alloy.Globals.drawer.openLeftWindow();
}, 100);
```

I'll try to find a way to fix this within the module.
