### ISSUE TITLE
Drawer on top of ActionBar

### ISSUE THREAD

**Issue by deckameron** [manumaticx/Ti.DrawerLayout#24]
Hi @manumaticx,

Thank you for this amazing module.
Is it possible?
![m2m2e](https://cloud.githubusercontent.com/assets/4404942/7071566/801bd85a-debc-11e4-9e38-5690faa92369.png)
![uog9b](https://cloud.githubusercontent.com/assets/4404942/7071567/8020858a-debc-11e4-8c40-cde3f11b9463.png)

**Comment by manumaticx** [comment]
I'm going to to add this feature in the next version which will add support for Material Theme and require Titanium 4.0.0

**Comment by deckameron** [comment]
Thank you, @manumaticx!

**Comment by manumaticx** [comment]
[TIMOB-17964](https://jira.appcelerator.org/browse/TIMOB-17964) is currently blocking the progress on this issue as I'm trying to follow this guide [here](http://www.android4devs.com/2014/12/how-to-make-material-design-navigation-drawer.html)

**Comment by victorgoh** [comment]
Support for this feature and Material Theme will be awesome!

**Comment by manumaticx** [comment]
@victorgoh definitely! But we need this resolved first: [TIMOB-17964](https://jira.appcelerator.org/browse/TIMOB-17964)

**Comment by Anatidae-Project** [comment]
Check out this:
https://github.com/Anatidae-Project/Ti.DrawerLayout/tree/ToolBar_Support

If you turn off the Actionbar in the manifest (tiapp.xml) and then use this code, you'll have the new Toolbar widget.

It would probably be pretty easy to set the toolbar visibility to GONE if an ActionBar already exists. In which case the module would only add in the toolbar if nothing is already there. Or, well, you could also add in a parameter to turn on/off Toolbar as well. To cover the base where someone doesn't want to have any sort of ActionBar/Toolbar.

Anyway. If you are like me and need to the new style, you can pull down this module from my branch and build it.

**Comment by manumaticx** [comment]
@Anatidae-Project  Oh wow! This really works that easy? I'm definitely going to test this today.

Is the Ti.Android.Actionbar and Ti.Android.Menu still working with the Toolbar?

**Comment by manumaticx** [comment]
@Anatidae-Project It works very fine! This is awesome! 

Let's integrate this here. I'll try to find a way how this could be turned on by option.

**Comment by Anatidae-Project** [comment]
@manumaticx Yes. I actually use ActionBarExtras. 
The key is to disable the toolbar completely in the manifest. You have to use a style that has no actionbar. Like this: Theme.AppCompat.Light.NoActionBar

Now, in the drawer module, it can then get the activity and use setSupportActionBar() to set up the new toolbar. After that, it works just like the standard actionbar.

So, today I'm going to follow your pattern and add in a property for useToolbar. I'll also hide the toolbar in the drawer_main.xml layout if the Titanium build already has a toolbar.

The logic will flow thusly:
1. Check to see if an actionbar already exists. If so, use that and continue on.
2. If no actionbar is present, check to see if the toolbar is set to be active.
3. Make the toolbar visible
4. Set it by activity.setSupportActionBar(toolbar)

At that point. Nothing else should need to be changed. I'll put a PR up in a few hours for it for you to check out.

**Comment by Anatidae-Project** [comment]
Here is the thing, I think you'll have to use this solution for Titanium going forward. If they put, in the main layout, a Toolbar, I'm not sure it is easy to remove that. Once you set your supportActionBar for an activity.... I've never tried removing a reference like that. It definitely isn't a supported pattern.

With the new toolbar, it has to be part of the layout in some way. So if you have a drawer, basically you put the toolbar above the container you want to use for your drawer.

**Comment by Anatidae-Project** [comment]
So, while @manumaticx tests and adjusts my PR. If you really need the new toolbar in Titanium 4.x.x, you can pull and build this branch:
https://github.com/Anatidae-Project/Ti.DrawerLayout/tree/ToolBar_Support

Or download the compiled module here:
https://github.com/Anatidae-Project/Ti.DrawerLayout/blob/ToolBar_Support/dist/com.tripvi.drawerlayout-android-1.3.5.zip

Please note that this probably should be fully tested. It's working in our app that is in beta and I'll fix any issues that come up.

**Comment by Bradleycorn** [comment]
So, I compiled the lastest master branch against 5.1.0.GA, and used the module in my app (also using 5.1.0.GA), and I can successfully toggle the Toolbar/ActionBar by changing my root theme to inherit from either
Theme.AppCompat.Light.NoActionBar (use Toolbar with drawer rendered over the toolbar)
Theme.AppCompat.Light.DarkActionBar (uses Actionbar - drawer is rendered below actionbar)

This is awesome!!!    Except ...
If the drawer is open (clicking the menu icon, or swiping in from the left), and then I click the device's back button, it doesn't close the drawer (as expected, and as it does in other Google apps). Instead the whole app (well, technically the current activity) closes. doh!

Am I doing something wrong? 

I'm familiar with the basics of native android development, but I'm not real familiar with the NavigationDrawer specifically.

**Comment by chmiiller** [comment]
thats awesome @Brian-McBride ! Any progress on this "back button" issue @Bradleycorn ?
Great job guys!

**Comment by deckameron** [comment]
Hi @chmiiller,

Maybe this code can help you. I haven't tested it yet but it seems ok.
```
window.addEventListener('android:back',function(){
	if(drawer.isRightDrawerOpen){ //Right Drawer
		drawer.closeRightWindow();
	}else if(drawer.isRightDrawerOpen){ //Left Drawer
		drawer.closeLeftWindow();
	}else{
		window.close();
	}
});
```

**Comment by manumaticx** [comment]
Updated Demo App: https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App

**Comment by chmiiller** [comment]
OMG this is a like a dream come true! Thanks =)

**Comment by manumaticx** [comment]
I've opened a new issue for the back button issue #58

I'll also update the documentation asap

**Comment by mano-mykingdom** [comment]
:+1: great job.
