### ISSUE TITLE
rightView:null still lets the slide gesture darken the screen

### ISSUE THREAD

**Issue by deckameron** [manumaticx/Ti.DrawerLayout#25]
@manumaticx;

I am creating my drawer like this:

var drawer = DrawerModule.createDrawer({
        leftDrawerWidth: "260",
        leftView:  tableView,
        centerView: centerView,
        drawerIndicatorEnabled: true,
        drawerArrowIcon: true,
        drawerArrowIconColor: '#FFF'
});
window.add(drawer);

There are no rightView being set but when I slide from the right edge of the screen it goes back like there was a menu to be shown.

I have tried setting the rightView to null, but I got no luck.

Am I doing anything wrong?
Thank you!

**Comment by manumaticx** [comment]
Hm,  your code looks okay with the exception of `drawerIndicatorEnabled ` and `drawerArrowIcon ` both set to true. You can have either the common drawer indicator or the drawer arrow animation.

But I'm not sure what causes this behavior. What version do you use?

**Comment by deckameron** [comment]
I am using SDK 4.0.0 and the module version is 1.3.0.

**Comment by manumaticx** [comment]
Ok, I'm going to test this.

**Comment by deckameron** [comment]
Thank you! :-)

**Comment by manumaticx** [comment]
@deckameron I'm sorry, I can not reproduce this. 

Can you transfer this behavior to the [demo app](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App)?

**Comment by deckameron** [comment]
Ok. I will do it! :)

**Comment by deckameron** [comment]
@manumaticx,

I have just found the problem.
I searched my code and I found a "drawer.rightDrawerWidth = "260";" lost in the open event of my window. :-/ My bad!

Sorry for bothering you with this and thank you for your attention.

**Comment by manumaticx** [comment]
@deckameron  :v:
