### ISSUE TITLE
Fancy arrow spin without showing the left or right Views

### ISSUE THREAD

**Issue by deckameron** [manumaticx/Ti.DrawerLayout#26]
@manumaticx ,

Is it possible to make the arrow spin and go back programatically without making the left or right View appear?

I am thing about changing the centerView and also turn the hambuger into the fancy arrow so that the user can click it and go back to the first center view and change the fancy arrow back to hambuger.

Thank you again!

**Comment by manumaticx** [comment]
@deckameron Not yet. But this would be useful indeed. I'm going to think about how this functionaloty could be integrated.

**Comment by manumaticx** [comment]
Hi @deckameron,

I've added a function which lets you set the arrow state. You could use it like this:

```js
var isArrow = false; // false = hamburger, true = arrow
function switchArrow(){
	Alloy.Globals.drawer.setArrowState(isArrow ? 0 : 1);
	isArrow = !isArrow;
}
```

**Comment by deckameron** [comment]
Hi @manumaticx,

Thank you very much for creating this! You are awesome! :-D

**Comment by nuno** [comment]
@manumaticx hey is possible chance the hamburger icon programaticly?

Ex. If a user is loggin show x icon if not show the default.

Hi @manumaticx <https://github.com/manumaticx>,

Thank you very much for creating this! You are awesome! :-D

—
Reply to this email directly or view it on GitHub
<https://github.com/manumaticx/Ti.DrawerLayout/issues/26#issuecomment-99834650>
.

**Comment by manumaticx** [comment]
@nuno I didn't test it but it should be possible to change the icon by setting a `homeAsUpIcon` with [ABX](https://github.com/ricardoalcocer/actionbarextras) - but you won't get the hamburger back then. So, we would need to add something here to make this possible.

**Comment by nuno** [comment]
@manumaticx Thank you!
