### ISSUE TITLE
Possible massive improvements for DrawerLayout

### ISSUE THREAD

**Issue by Anatidae-Project** [manumaticx/Ti.DrawerLayout#28]
http://www.androidpolice.com/2015/04/21/major-update-to-android-support-library-22-1-introduces-appcompatactivity-adds-major-theming-improvements-and-tons-of-backward-compatibility/

This is really interesting news. If Titanium 4.0 would inherit from [AppCompatActivity](http://developer.android.com/reference/android/support/v7/app/AppCompatActivity.html?utm_campaign=ASL221-415&utm_source=dac&utm_medium=blog) then I think we might be able to take advantage of more of the Material designs, such as the drawer over the toolbar.

**Comment by Hollerweger** [comment]
I have committed a Demo Version with added Material Theme and tinted action bar and status bar using theme attributes working with Titanium SDK 4.0.0RC+: 
https://github.com/Hollerweger/Ti.DrawerLayout-Demo-Alloy-App

**Comment by nuno** [comment]
@Hollerweger I did that some time ago https://github.com/nuno/Ti.DrawerLayout-Demo-Alloy-App
what you think?

**Comment by Hollerweger** [comment]
@nuno nice to see. The difference is that your example requires API level 21 (or I'm wrong?).
Mine uses AppCompat which is a support library that is backward compatible to API level 7. AppCompat is directly supported by Titanium SDK 4.0.0RC+. So it was really easy to implement: https://github.com/Hollerweger/Ti.DrawerLayout-Demo-Alloy-App/commit/2d5daec3ee359f8b505685c5d4076b03c111ad7d
For more infos regarding theming with AppCompat: http://android-developers.blogspot.co.at/2014/10/appcompat-v21-material-design-for-pre.html

What I'm searching for would be a solution where I could use this module for android and a TabGroup on iOS with one menu definition. @nuno Do you know how to archive that?

**Comment by nuno** [comment]
@Hollerweger sorry no.

**Comment by jpriebe** [comment]
My TitanUp library (https://github.com/jpriebe/TitanUp) defines a DrawerMenuWM (drawer menu window manager) that gives you a cross-platform drawer menu for android and iOS (not a tab for iOS, but a menu much like Ti.DrawerLayout).  On iOS, this can be achieved with just Titanium views.

**Comment by manumaticx** [comment]
Hey guys, thanks for your suggestions and demos. I'd like to close this issue. If you have particular issues according to Material theme please feel free to open issues here (e.g. there's already an issue for full-height drawer, which will be added as soon as Titanium supports the toolbar)
