### ISSUE TITLE
posible memory leaks?

### ISSUE THREAD

**Issue by falkolab** [manumaticx/Ti.DrawerLayout#29]
I trying to open chain identical windows. When open more then one window and then close all except one I found this case make memory leaks.
You can track sample code in DDMS.
```
var TiDrawerLayout = require('com.tripvi.drawerlayout');
var counter = 1;
var windows = [];
function createDrawerWindow() {
    var win = Ti.UI.createWindow();

    var contentView = Ti.UI.createView({layout : "vertical"});
    
    var view = Ti.UI.createLabel({text : 'Window #' + counter++});
    contentView.add(view);
    
    view = Ti.UI.createButton({title : "open another window"});
    view.addEventListener('click', openNewOne);    
    contentView.add(view);
    
    view = Ti.UI.createButton({title : "close this window"});
    view.addEventListener('click', closeCurrent);
    contentView.add(view);
    
    view = null;

    var leftView = Ti.UI.createTableView({backgroundColor : '#ccc'});

    var drawer = TiDrawerLayout.createDrawer({
        centerView : contentView,
        leftView : leftView,
        width : Ti.UI.FILL,
        height : Ti.UI.FILL
    });
    
    contentView = null;
    leftView = null;
    
    win.add(drawer);
    windows.push(win);
    return win;
}


function openNewOne(evt) {
    //evt.source.removeEventListener(evt.type, openNewOne);
    createDrawerWindow().open();
}

function closeCurrent(evt) {
   // evt.source.removeEventListener(evt.type, closeCurrent);
    var win = windows.pop();
    win.removeAllChildren();
    win.close();
}


createDrawerWindow().open();
```

**Comment by manumaticx** [comment]
Thanks for pointing this out. I'm going to test this soon. But what I can see in the code without testing is a missing `var` at this line:
```js
drawer = TiDrawerLayout.createDrawer({
```
This could be a possible reason for a memory leak.

**Comment by falkolab** [comment]
Sorry, its my typo, but it no matter. Also result leaks. This is very serious for my project. User open and close windows with drawer many times. That leads to app freezes and crashes.

**Comment by manumaticx** [comment]
@falkolab  Ok, I've just tested this code. Where do you think it is leaking? I can't see any differences in the allocation tracker if I open 1 window or 10 windows.

**Comment by falkolab** [comment]
1. open fresh app with one window opened 
http://joxi.ru/4vAWWxVtOLOGAW
2. open another 9 windows, press GC button
http://joxi.ru/el2ZKy3s7Q7WAJ
3. close 9 windows, press GC any times
http://joxi.ru/Ra2Xlk7U4W4z2g

Allocated memory: step1 != step3. 
Leak: ~ 4mb

**Comment by falkolab** [comment]
Same example without drawer for comparison:
```
var counter = 1;
var windows = [];

function createWindow() {
    var win = Ti.UI.createWindow();

    var contentView = Ti.UI.createView({layout : "vertical"});
    
    var view = Ti.UI.createLabel({text : 'Window #' + counter++});
    contentView.add(view);
    
    view = Ti.UI.createButton({title : "open another window"});
    view.addEventListener('click', openNewOne);    
    contentView.add(view);
    
    view = Ti.UI.createButton({title : "close this window"});
    view.addEventListener('click', closeCurrent);
    contentView.add(view);    
    
    
    win.add(contentView);
    windows.push(win);
    return win;
}


function openNewOne(evt) {
    //evt.source.removeEventListener(evt.type, openNewOne);
    createWindow().open();
}

function closeCurrent(evt) {
   // evt.source.removeEventListener(evt.type, closeCurrent);
    var win = windows.pop();
    win.removeAllChildren();
    win.close();
}


createWindow().open();
```

**Comment by falkolab** [comment]
Have any of contributors can confirm this issue?

**Comment by manumaticx** [comment]
@falkolab Can you please test this again with 1.3.3 ? (@mano-mykingdom has come up with a fix that maybe closes the leak)

**Comment by manumaticx** [comment]
Considered as fixed. Feel free to reopen.

**Comment by falkolab** [comment]
Yes 1.3.4 has also memory leaks. I have to find for another solution :(

**Comment by manumaticx** [comment]
Okay, thanks for testing

**Comment by falkolab** [comment]
I found Titanium SDK 4.1.0.GA has memory leak in common Ti.UI.Window https://jira.appcelerator.org/browse/TC-5648. 
Therefore I can't test this issue in the 4.1.0.GA SDK. And also I can't  run test case project with combination this module 1.3.4 and Titanium SDK 3.5.1.GA

**Comment by falkolab** [comment]
Due some serious bug in the Ti SDK 4.1.0.GA I can't migrate my project to it and I can't test last version of this module, because: https://github.com/manumaticx/Ti.DrawerLayout/commit/35181a63df434509953369fbb268fe86d35292a3#diff-fa26c54e383e760978703a6f87daf46d

For 1.3.0 drawer module version  I found memory leak with left view, it holding ViewProxy in memory after Window closing.

**Comment by manumaticx** [comment]
Can you try 1.3.3? That was where the centerView leak was fixed: https://github.com/manumaticx/Ti.DrawerLayout/commit/9fc3435e46b944efb5fe1c3ccfffcd5e26972df3

**Comment by manumaticx** [comment]
I see, leftView and rightView needs to be removed from layout too.

**Comment by manumaticx** [comment]
https://github.com/manumaticx/Ti.DrawerLayout/pull/45
Can you please review and test this?

**Comment by falkolab** [comment]
I can't do complex test with my project that targeted to Ti SDK 3.5.1.GA. Your last changes not usable for me.

**Comment by falkolab** [comment]
No, I can't test this chages due Ti SDK has memory leak begining from 4.0.0.GA as it mentioned above. Is it possible to backport your changes around ActionBarDrawerToggle for possibility to build for Ti SDK 3.5.1?

**Comment by manumaticx** [comment]
I thought the activity lifecycle events were added in 4.0.0 but it seems to work with 3.5.1.GA. I've pushed this to a separate branch here: https://github.com/manumaticx/Ti.DrawerLayout/tree/3_5_1_backport

**Comment by falkolab** [comment]
Yes lifecycle events work with 3.5.1. I play with cleanup and later notify to you about results.

**Comment by falkolab** [comment]
I spent a week on a study of this question. I made a few corrections (not published) in the module that caused the leak. But I can not quite understand why, even when I close the window in memory remain proxy objects. Alloy or not no matter.

Another example, I open one window after another 10 times, but in the memory there are 4 WindowProxy with his child views etc.. Why not one?!

**Comment by manumaticx** [comment]
Wow, really appreciate your efforts!

So as for my understanding, there's a combination of issues causing memory leaks. On the one hand the WindowProxy bug in 4.1.0 and on the other hand some things in this module.

Do you think this change could also be a possible reason? https://github.com/appcelerator/titanium_mobile/commit/3e752624eb428bf98480463f144388ea6d4180e1

I'm really looking forward to a solution for [TC-5648](https://jira.appcelerator.org/browse/TC-5648).

And if you could send a pull request with your corrections on this module, that would be awesome! Have you had a look on #45 ? Does that make sense? If you don't have any worries I'd like to merge this too.

Thank you! :)

**Comment by falkolab** [comment]
No https://github.com/manumaticx/Ti.DrawerLayout/pull/45 not needed because I use overrided method releaseViews of drawer proxy. I'm trying to implement multiple windows with drawer but not all View proxies propertly removed by Garbage collector. I do not know why. Now I use only 3.5.1.GA.
I will do pull request later. 

I wonder why remain in memory several proxy objects after several cycles open and close simple window. And count of remain objects less then windows opened even if I was not add drawer to that windows.

Now I think to use your example with one window with several view controllers but that lead many changes in my complex project

**Comment by manumaticx** [comment]
Closing this as this is a Titanium bug: https://jira.appcelerator.org/browse/TIMOB-19891
