### ISSUE TITLE
drawer.setDrawerIndicatorEnabled not working or crashing the app.

### ISSUE THREAD

**Issue by deckameron** [manumaticx/Ti.DrawerLayout#30]
Hi @manumaticx 

I was trying to remove the fancy arrow icon and show the normal icon back and this error happened:

[ERROR] :  TiApplication: (main) [6605,6948] Sending event: exception on thread: main msg:java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference; Titanium 4.0.0,2015/03/30 10:58,f480474
[ERROR] :  TiApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference
[ERROR] :  TiApplication: 	at com.tripvi.drawerlayout.Drawer.propertyChanged(Drawer.java:640)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollPropertyChange.fireEvent(KrollPropertyChange.java:21)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1083)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:347)
[ERROR] :  TiApplication: 	at com.tripvi.drawerlayout.DrawerProxy.handleMessage(DrawerProxy.java:70)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:135)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

My code is this:
```
var drawer = TiDrawerLayout.createDrawer({
	leftDrawerWidth: "260",
	leftView: menuTable,
	centerView: contentView,
	drawerArrowIcon: true,
	drawerArrowIconColor: '#FFF'
});

var button = Ti.UI.createButton({
	top: "75dp",
	title: "Change  Icon"
});

button.addEventListener("click", function(e) {
	drawer.setDrawerArrowIcon(false);
	drawer.setDrawerIndicatorEnabled(true);
});
contentView.add(button);
```

**Comment by manumaticx** [comment]
The drawer icon is not intended to be changed after initialization. 

`drawer.setDrawerIndicatorEnabled()` fails because the drawer was initialized with `drawerArrowIcon: true` so there is no actual drawerIndicator that can be enabled / disabled. I can catch that error but it won't work anyway.

The reason for this is that the `drawerArrowIcon ` is actually just a custom up-icon. It is not the actual drawerIndicator but rather a [backport](https://github.com/ChrisRenke/DrawerArrowDrawable) that this module uses as a workaround for the official ActionBarDrawerToggle.

**Comment by deckameron** [comment]
I see!
I was trying to change the icon into a back arrow after i change the center view, in order to show the user its possible to go back. It would a workaround until you have some time to implement that #26 . :-)
Thank you for your help!

**Comment by manumaticx** [comment]
catching the error now 24d39043423ea6e504121c0f5fe8d3468b57c4c4
