### ISSUE TITLE
DrawerLayout with TabGroup

### ISSUE THREAD

**Issue by deckameron** [manumaticx/Ti.DrawerLayout#32]
Hi @manumaticx,

Do you have plans to make DrawerLayout work with TabGroup? Or it is not possible at all to be accomplished (Titanium limitation)?

Thanks!

**Comment by manumaticx** [comment]
Hi @deckameron 

it should be possible. But I think it requires some refactoring work. The Drawer module is built to work with views whereas the TabGroup is implemented as a standalone Window. I really want to accomplish this functionality. I hope I can have a look at this again soon.

Thanks

**Comment by deckameron** [comment]
I understand, @manumaticx!
One solution for this "problem" is to combine the DrawerLayout with your PagingControl. It works perfectly. :-)

**Comment by manumaticx** [comment]
Yeah, any view-based approach is a workaround. But I also would love to see native Actionbar-Tabs playing together with the Drawer in Titanium

**Comment by manumaticx** [comment]
Hi @deckameron 

I've just had a look at this again and I'm afraid there's no way to accomplish this with the current implementation of Titaniums TabGroup. The TabGroup is designed to act as root window replacement and you act windows to the tabgroup. It does not work the other way. You can't have a window as your root (with drawer) and add a TabGroup to it.

In addition, the Android guides used to state out that you should not combine a NavigationDrawer and a TabGroup as both are designed for Top-Level-Navigation. Check out Roman Nurik's answer on [this discussion](https://plus.google.com/u/0/+DavidTaSmoochibi/posts/8dWEkFcbTFX). At least pagingcontrol is a workaround :)

Another workaround could be adding the Drawer to one or more windows within the TabGroup. I know that Rainer Schleevoigt was using this (see [this comment](https://github.com/manumaticx/Ti.DrawerLayout/issues/4#issuecomment-76747116)).

I hope this helps you. So, I'd like to close this issue as I don't think this is going to be implemented.

**Comment by LeoLeal** [comment]
Sorry for reviving an old discussion, I was reading the documentation and found no solution to implementing the Drawer with Tab group, and just came across this issue.

Just adding to the conversation, that It is actually part of the specification to combine drawer and tab group according to the guidelines.

[https://material.google.com/patterns/navigation.html#navigation-combined-patterns](https://material.google.com/patterns/navigation.html#navigation-combined-patterns)

**Comment by manumaticx** [comment]
@LeoLeal Thanks for the pointer.

That's right. As per the guideline Drawer and Tabgroup *can* be combined but only if you use the Drawer for top-level navigation and the Tabgroup for sub-level navigation.

In Titanium, the Tabgroup was implemented as top-level Navigation. That means in fact, if you want to use it, you have to use a Window for each Tab. There are no Fragments in Titanium. The Tabgroup has to be the root window, there is no way to add it to another parent.

I'm not sure if my understanding of this is 100% true but I don't see a way of fixing this within this module.

**Comment by LeoLeal** [comment]
Oh i see... the only solutsolutien would  be to implementar a module to override the Ti.UI.Tabgroup namespace for the Alloy  tag <Tabgroup> for Android, right?

**Comment by manumaticx** [comment]
That's actually not possible. Also, this isn't a namespace or Alloy issue. This has to be fixed in the Titanium core.
Alternatively you could use a View-based solution that acts like a tab-group, e.g. ScrollableView with my [paging-control](https://github.com/manumaticx/pagingcontrol) widget.
