### ISSUE TITLE
Can't hide action bar if using Theme.AppCompat.Light

### ISSUE THREAD

**Issue by dyan02** [manumaticx/Ti.DrawerLayout#35]
Hi, after i upgrade to titanium 4.0.0 GA, if i use Theme.AppCompat.Light, the action bar will shows, even though i already hide the action bar in the custom_theme.xml. This will not happen if i use Theme.Titanium. Thanks.

**Comment by manumaticx** [comment]
Hi @dyan02 
Does that only happen with this module? It seems like a general Titanium question.

**Comment by dyan02** [comment]
sorry my mistake. Thanks for the reminder
