### ISSUE TITLE
Issues since drawerlayout placed inside TiCompositeLayout 

### ISSUE THREAD

**Issue by mano-mykingdom** [manumaticx/Ti.DrawerLayout#38]
* **replaceCenterView - keeps adding new view to the drawerlayout. The previous views are never removed.**
* replaceCenterView - backstack param not considered / used

**Comment by manumaticx** [comment]
Thanks @mano-mykingdom 

I'm aware, there are problems with `replaceCenterView` (the proxy method) as discussed in #34 and #37 and I thought about just dropping that method.
