### ISSUE TITLE
support MapView

### ISSUE THREAD

**Issue by manumaticx** [manumaticx/Ti.DrawerLayout#4]
ref: https://github.com/Tripvi/Ti.DrawerLayout/issues/7

**Comment by mokesmokes** [comment]
The Ti.map API will need to be modified to receive the container somehow.

**Comment by manumaticx** [comment]
@mokesmokes Thanks for having a look. I really was hoping for your help!

As I [commented on the ti.map issue](https://github.com/appcelerator-modules/ti.map/issues/77#issuecomment-72496676) the TiUIFragment instance seems to lose its self-created container. I'm not sure if this is only happens when nesting the map in another fragment because the crash can be reproduced without a parent fragment. A simple test is the code in the ticket:
```javascript
Ti.UI.createAlertDialog({
    androidView: require('ti.map').createView()
}).show();
```
Do you have any idea what could be the reason? I really appreciate your investigation!

**Comment by mokesmokes** [comment]
The reason is that you need to add the map to your fragment, but the current Ti.Map and TiUiFragment have no reference to your fragment. So basically, this functionality needs to be added. See http://stackoverflow.com/questions/13733299/initialize-mapfragment-programmatically-with-maps-api-v2 for maps in a fragment.

**Comment by muka** [comment]
Hi @mokesmokes 
I've worked a bit on the ti.map module and I'd be happy to help out on this. 

I've tried following the approach you used in this commit (https://github.com/appcelerator/titanium_mobile/commit/f1925ac69c1a09ddc99c75f11be54cf1bd3483ee) and in the link above (by extending SupportMapFragment) with no luck, the same error pop out (resource not found)

I've also tried to "clone" the TiUIFragment for the ti.map View (based on the 3.5.0.GA code), adding a custom tag to the fragment and checking then in the drawer code for it. 
Same also with container id (which seems to be the default beahviour) 

After some experiments, the FragmentManager doesn't know about the MapFragment, even if specified via tag. Seems it is not yet available, I still would like to try by forcing the transaction ( `executePendingTransactions`)

Could you help a bit describing which functionality is missing?

Thank you very much
Regards

**Comment by Anatidae-Project** [comment]
Has anyone gotten a maps module build that will work with the drawer? 

I think that the maps module needs love in general. Sometime in the last gear getRegion() broke on Android. Of course, that matters little when the map crashes the app in the drawer here.

By the way, this will also crash other popular drawers like dk.napp.drawer.

**Comment by john-dalsgaard** [comment]
Thanks for your effort on solving this. I am afraid I don't have the skills (yet) to help out on solving it....

Stuck with same issue - and also realizes that all drawers seem to run into this issue :-(

**Comment by AppWerft** [comment]
In my case the app doesn't  crash, but the view keeps empty. Next try: embedding of mapview in a view container and this container is „contentView“ of drawer: same result.
![screenshot_2015-03-02-17-39-19](https://cloud.githubusercontent.com/assets/2996237/6445294/4565f85c-c103-11e4-83d8-1e48923cc22e.png)

**Comment by manumaticx** [comment]
Okay, this can be considered as fixed - whoop! :smiley:

Please follow the testing steps here: [TIMOB-18244](https://jira.appcelerator.org/browse/TIMOB-18244)

Massive thanks to @hieupham007 for his excellent work on this issue!

**Comment by marconealberto** [comment]
it's still crashing on my side. I tried to wrap the mapView in a View but it still crashes.

```xml
<Alloy>
	<Window module="xp.ui" role="main">
		<LeftNavButton platform="ios">
			<Require src="_menuButton" />
		</LeftNavButton>
		<View height="Ti.UI.SIZE" layout="vertical">
			<Module id="mapview" module="ti.map" method="createView" />
		</View>
	</Window>
</Alloy>
```
