### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by Yakito** [manumaticx/Ti.DrawerLayout#41]
Hello,

I just upgraded the module to 1.3.3 from 1.2.2 and now the app is complaining about an error when I try calling a second view.

I am using the exact same code which was working on 1.2.2 calling the secondWindow using the following function:

    function replaceCenterView(args){
      var view = Alloy.createController('secondWindow',args).getView();
      Alloy.Globals.drawer.replaceCenterView(view, true);
    }

The error is the following

    Only the original thread that created a view hierarchy can touch its views

I found out that if I change this

    Alloy.Globals.drawer.replaceCenterView(view, true);

for this 

    Alloy.Globals.drawer.replaceCenterView(view);

The error goes away, but then nothing happens, and the SeconView is not visible.

Any tip on how to solve this will be appreciated! 
Thanks a lot!

**Comment by manumaticx** [comment]
Please use `setCenterView()` to change the centerView.

The `replaceCenterView` method will be removed soon. Since version 1.3.3 this module does not warp the centerView within Fragments anymore. So this method does not make sense anymore.

**Comment by Yakito** [comment]
Thanks! it is working now!
