### ISSUE TITLE
Can't compile source (can't resolve ui package)

### ISSUE THREAD

**Issue by Bradleycorn** [manumaticx/Ti.DrawerLayout#42]
Trying to compile from the source, I've got an error in the Drawer.java that I can't solve.

import ti.modules.titanium.ui.WindowProxy;

I get an error "the import ti.modules.titanium.ui cannot be resolved". 

I've tried referencing the titanium.jar from both the 4.0.0.GA sdk and the 3.5.1.GA sdk with no luck. Is there some trick to getting the compiler to find ti.modules.titanium.ui ??

**Comment by Bradleycorn** [comment]
hrm, guess this is more of a question than a problem. Eclipse (Appcelerator Studio) shows it as an error, but the module does compile fine. Interesting.

**Comment by manumaticx** [comment]
You have to add the `titanium-ui.jar` lib to your build path. 
Configure Build Path > Add external JAR > ... and then select `~/Library/Application Support/Titanium/mobilesdk/osx/4.0.0.GA/android/modules/titanium-ui.jar` (or add it manually to your _.classpath_ file)

**Comment by Bradleycorn** [comment]
Awesome, that did the trick. thanks!

**Comment by manumaticx** [comment]
You're very welcome! :+1:

**Comment by Bradleycorn** [comment]
2 follow up questions:

1.) I noticed a "material" branch (presumably for adding material design support). Is that functioning, or still a work in progress?

2.) If it's still a work in progress and I wanted to contribute, is there anything in particular that it would be best to work on

**Comment by manumaticx** [comment]
1. This was just for testing and fooling around. I'll delete it asap. Just pushed it to share my progress with Geraud.

2. As discussed on [gitter](https://gitter.im/manumaticx/Ti.DrawerLayout) this is blocked by the lack of Toolbar support. Not sure what else we could do... (but if you want to contribute, please use the master branch)
