### ISSUE TITLE
Cannot add window/tabGroup to a view under 4.1.0 GA

### ISSUE THREAD

**Issue by Yakito** [manumaticx/Ti.DrawerLayout#43]
Hello, I just installed 4.1.0 on my app which was previously working fine with DrawerLayout and now each time I click on an item in the menu I am getting:

    /view.js
    Cannot add window/tabGroup to a view

None of my views uses tabGroups, so I am not sure why the error is firing. Any tip will be appreciated!
Thanks!

**Comment by Yakito** [comment]
My bad, it looks like while in 4.0.0 GA each controller could have a <Window> tag, under 4.1.0 GA throws out the error, but that makes totally sense. By changing <Window> for <View> it works again. Sorry about that.

**Comment by Prakhs** [comment]
Hi Yakito,

Can you please let me know, how did you resolve this issue in detail?

Thanks

**Comment by SamBishop25** [comment]
how did you resolve this issue?

**Comment by Prakhs** [comment]
I was having window in one of my widget and that was causing the problem,
and this widget was required in a window. So you can check your code and
you can change that window to view.
