### ISSUE TITLE
Using left and right menu 

### ISSUE THREAD

**Issue by nubu** [manumaticx/Ti.DrawerLayout#47]
Hey,

I'm trying to use both, left and right side slides. The Problem is: The arrow on the topleft corner is spinning if I'm opening the  right slide. (Pressing on it after that, will trigger the left slide to slide in)

Strange behavier - any idea?

**Comment by manumaticx** [comment]
@nubu Thanks for reporting this! That's definitely not intended. But I know what's going on here. I've fixed this (a year ago)[https://github.com/Tripvi/Ti.DrawerLayout/pull/28] but re-introduced the bug by accident when moving to native ActionBarDrawerToggle (v1.3.4).

**Comment by nubu** [comment]
:+1:
