### ISSUE TITLE
Enhancement:  Possible to define how much of left area to detect swipe in?

### ISSUE THREAD

**Issue by mark22** [manumaticx/Ti.DrawerLayout#48]
Right now you literally have to swipe from offscreen to open the menu.  Is it possible to change this number to a user defined number, for example say if someone swipes anywhere in the left 33% of the screen it would detect as a swipe to open the menu?

Thank you!!!

**Comment by manumaticx** [comment]
There's no property that we could use straight away. But it is possible. I could implement this solution somebody figured out [here](http://stackoverflow.com/questions/16988597/set-drag-margin-for-android-navigation-drawer/17802569#17802569).

**Comment by manumaticx** [comment]
added here: ba60f7bb0fc472da363947842097d7b02e36f6ed
