### ISSUE TITLE
change actionbar color

### ISSUE THREAD

**Issue by hyabusa** [manumaticx/Ti.DrawerLayout#51]
is there a way to change action bar coloor in android from black to something else? i am adding "res" in android with custom colors but no changes. if i remove Ti.DrawerLayout module, i can see the color changge in action bar. but with Ti.DrawerLayout module it always stays black.

**Comment by manumaticx** [comment]
There's two packaged versions of the module in /dist:
* com.tripvi.drawerlayout-android-1.3.5.zip
* com.tripvi.drawerlayout-android-1.4.0-alpha-1.0.zip

You should not use the second one yet. It's a little bit confusing but both packages are version 1.3.5 just with a different package name.

There shouldn't be a problem with the Actionbar as the "old" version does not affect it.
