### ISSUE TITLE
Open new window

### ISSUE THREAD

**Issue by bcarvalho89** [manumaticx/Ti.DrawerLayout#59]
Hello!
I'm trying to open a new window but the action bar does not appers. If I open with `modal:true`, the action bar appers without styles.
Below exemplify what happen:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/8310877/14051599/0961e334-f2a3-11e5-9064-48c43f6022a4.gif)

Any chance to fix it?
Thanks for attention

**Comment by manumaticx** [comment]
This is because the drawer requires a NoActionBar theme (it adds a Toolbar within tis own layout). In the demo app that theme was used by default. I just fixed it [there](https://github.com/manumaticx/NavigationDrawer-Demo/commit/4bce6dd0952207c69a70b7125c61c8576b06f202). Did this help you?

**Comment by bcarvalho89** [comment]
Helps a lot! 
In new window, the text color was black and status bar was gray.
I must add this two lines in themes.xml:

```
<item name="colorPrimaryDark">@color/primaryDark</item>  
<item name="android:textColorPrimary">#ffffff</item>
```

Thanks again.

**Comment by manumaticx** [comment]
Ah yes. Great! :)
