### ISSUE TITLE
Action bar below the status bar

### ISSUE THREAD

**Issue by arshavinho** [manumaticx/Ti.DrawerLayout#62]
Hello,

i'm using Titanium SDK 5.2.2 GA (also tried with 5.2.0 GA), with Samsung S5 with android 5.0, when i tried to implement the module in my App i noticed that the action bar is below the status bar so i tried the demo App and the same behaviour occurs. Do you have any idea of what i could forget ? Thanks

Screenshot:

![drawerstatusbarbug2](https://cloud.githubusercontent.com/assets/1016441/14671232/12e61fe4-06f1-11e6-894f-2c72b6f96490.png)

**Comment by manumaticx** [comment]
Depending on what behavior you want, there are two possible ways:

1. **drawer should overlay app bar**
then you have to add some padding to the actionbar. Again, two ways to achieve this:
 * tweak the layout in xml like in the [demo](https://github.com/manumaticx/NavigationDrawer-Demo/blob/master/modules/android/com.tripvi.drawerlayout/1.3.6/platform/android/res/layout/drawer_main.xml#L25)
 * add it dynamically with [ABX](https://github.com/ricardoalcocer/actionbarextras): `abx.setToolbarTopPadding(abx.statusbarHeight);`

2. **drawer should appear beneath toolbar**
then you have to use a Theme with Actionbar like `Theme.AppCompat.Light` and create the drawer with `hideToolbar: true`

**Comment by arshavinho** [comment]
Thanks, the tweak in the layout xml works great,
with ABX i had an error: TypeError: Object #<Actionbarextras> has no method 'setToolbarTopPadding'

**Comment by manumaticx** [comment]
@arshavinho  `setToolbarTopPadding` was added in ABX 1.6.9

**Comment by arshavinho** [comment]
thank you i was using 1.6.8
