### ISSUE TITLE
DrawerLayout and splash screen

### ISSUE THREAD

**Issue by arshavinho** [manumaticx/Ti.DrawerLayout#68]
Hello,

i used the example: https://github.com/manumaticx/NavigationDrawer-Demo
to implement your module with the themes.xml. After doing that, the splash screen doesnt show up at startup, only a window with the name of my app for title.

i tried to follow this guide for custom theme: "Splash Screen with a Custom Theme"  http://docs.appcelerator.com/platform/latest/#!/guide/Icons_and_Splash_Screens

but i got this error at compilation:  

"build/android/res/values/themes.xml:9: error: Error: No resource found that matches the given name: attr 'windowBackground'."

here my themes.xml where i just add "windowBackground" and "android:windowBackground":
I also have "backgroud.9.png" in drawable-.... folders, generate with tiCons.

<?xml version="1.0" encoding="utf-8"?>

<resources xmlns:android="http://schemas.android.com/apk/res/android">

    <style name="Theme.DrawerTest.NoActionBar" parent="@style/Theme.AppCompat.Light.NoActionBar">
      <item name="android:windowTranslucentStatus">true</item>
      <item name="colorPrimary">@color/primary</item>
      <item name="colorPrimaryDark">@color/primaryDark</item>
      <item name="windowBackground">@drawable/background</item>
      <item name="android:windowBackground">@drawable/background</item>
    </style>

</resources>

Do you have any idea ?

Thank you

**Comment by manumaticx** [comment]
Try removing this line:
```xml
<item name="android:windowBackground">@drawable/background</item>
```

**Comment by manumaticx** [comment]
Or try renaming the theme.xml.
> "Do NOT name the file theme.xml. Titanium uses this name as its default theme file, which is required to build the application. If you create a file called theme.xml, it will overwrite the default Titanium one and break the build process."
Could it be, this is the problem?

**Comment by manumaticx** [comment]
@arshavinho Were you able to resolve this?

**Comment by arshavinho** [comment]
Sorry for the delay, 

No i have an Android app on the market with no splash screen for now :'(

**Comment by arshavinho** [comment]
Hello,

The documentation mention to do not name the file theme.xml, my file name is "themes.xml", i try to rename it to "theme.xml" and the compilation failed like the documentation says.

Here my test:

themes.xml:

```
<?xml version="1.0" encoding="utf-8"?>

<resources xmlns:android="http://schemas.android.com/apk/res/android">
    <style name="Theme.DrawerTest.NoActionBar" parent="@style/Theme.AppCompat.Light.NoActionBar">
      <item name="android:windowTranslucentStatus">true</item>
      <item name="colorPrimary">@color/primary</item>
      <item name="colorPrimaryDark">@color/primaryDark</item>
	  <item name="windowBackground">@drawable/background</item>
	  <item name="android:windowBackground">@drawable/background</item>
    </style>
</resources>

```

Error:

```
[ERROR] :  Failed to package application:
[ERROR] :  
[ERROR] :  build/android/res/drawable-mdpi/background.9.png: libpng warning: cHRM: inconsistent chromaticities
[ERROR] :  build/android/res/drawable-hdpi/background.9.png: libpng warning: cHRM: inconsistent chromaticities
[ERROR] :  build/android/res/drawable-xhdpi/background.9.png: libpng warning: cHRM: inconsistent chromaticities
[ERROR] :  build/android/res/drawable-xxhdpi/background.9.png: libpng warning: cHRM: inconsistent chromaticities
[ERROR] :  build/android/res/drawable-xxxhdpi/background.9.png: libpng warning: cHRM: inconsistent chromaticities
[ERROR] :  build/android/res/drawable-mdpi/cancel_cce50b424e.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[ERROR] :  build/android/res/drawable-hdpi/cancel_cce50b424e.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[ERROR] :  build/android/res/drawable-xhdpi/cancel_cce50b424e.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[ERROR] :  build/android/res/drawable-xxhdpi/cancel_cce50b424e.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[ERROR] :  build/android/res/drawable-mdpi/menu_7d3cc7005f.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[ERROR] :  build/android/res/drawable-hdpi/menu_7d3cc7005f.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[ERROR] :  build/android/res/drawable-xhdpi/menu_7d3cc7005f.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[ERROR] :  build/android/res/drawable-xxhdpi/menu_7d3cc7005f.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[ERROR] :  build/android/res/values/themes.xml:9: error: Error: No resource found that matches the given name: attr 'windowBackground'.

```           

themes.xml:

```
<?xml version="1.0" encoding="utf-8"?>

<resources xmlns:android="http://schemas.android.com/apk/res/android">
    <style name="Theme.DrawerTest.NoActionBar" parent="@style/Theme.AppCompat.Light.NoActionBar">
      <item name="android:windowTranslucentStatus">true</item>
      <item name="colorPrimary">@color/primary</item>
      <item name="colorPrimaryDark">@color/primaryDark</item>
	  <item name="android:windowBackground">@drawable/background</item>
    </style>
</resources>
```

No error, but splash screen didn't show up.
