### ISSUE TITLE
does not working with android 6

### ISSUE THREAD

**Issue by AhmedMohamed2014** [manumaticx/Ti.DrawerLayout#69]
this made my app crushes with android 6 .. need updates

**Comment by manumaticx** [comment]
@AhmedMohamed2014 Can you provide some more information about the error?

**Comment by dave101** [comment]
error i'm getting is: [ERROR] :  linker: /data/app/<appname>/lib/arm/libcom.tripvi.drawerlayout.so: has text relocations

**Comment by dave101** [comment]
This occurs on android version 6.0 when targeting android sdk 23

**Comment by manumaticx** [comment]
I'll compile with latest NDK and hope it works out

**Comment by dave101** [comment]
Confirmed compiling with NDK 9+ fixes this. Therefore it seems it's a google bug and not the modules

**Comment by jpriebe** [comment]
Just so I understand what's going on here, are we talking about a compilation warning or an app crash?  We're building with android SDK 23 and our app runs fine on android 6.

**Comment by dave101** [comment]
When compiling the app using SDK 23 the App will crash on startup if the Module is compiled using an NDK prior to R9. 
Although; When compiling the App on an earlier version than 23, it is only a warning message.
