### ISSUE TITLE
Drawer discounts the Theme

### ISSUE THREAD

**Issue by manumaticx** [manumaticx/Ti.DrawerLayout#7]
All Views within the Drawer (centerView, leftView and rightView) are ignoring custom Themes.

Edit: Apparently this affects only some controls like textfields for example.

**Comment by nuno** [comment]
Hey @manumaticx  I just added support to android L at  https://github.com/nuno/Ti.DrawerLayout-Demo-Alloy-App/commit/bf13cddd364a4645bab163bb13504ec25dc98132

http://cl.ly/image/2X1t1P0f3N3E
and 
http://cl.ly/image/3o2Z321l3d2L

**Comment by manumaticx** [comment]
Hi @nuno 
thanks, this looks good!

**Comment by dyan02** [comment]
having this problem, try to apply custom theme, some parameter like spinner is ignored, any workaround for this? :) Thanks

**Comment by manumaticx** [comment]
@dyan02 not yet. Still don't know what causes that behavior. Sometimes it uses the correct theme, sometimes it does not. I have no idea how to approach this.

**Comment by dyan02** [comment]
i do have workaround for this, as long the drawerlayout is not called in the very first window, the custom theme will work,

so what i'm doing is i'm open dummy window, before open the main window (which containing the drawer layout)

**Comment by manumaticx** [comment]
@dyan02  Thanks a lot for this insight! This explains the reason for this behavior very well.

If the Drawer is created before the window is open it references the _current_ activity which is the launcher activity in case for the first window.

So another workaround (instead of opening a dummy window) is creating the Drawer after the window is open, e.g. like this:

```js
// win is the first window
win.addEventListener('open', function(){
  var drawer = TiDrawerLayout.createDrawer({
    // ...
  });

  win.add(drawer);
});
```

I've just tested this and it works fine. Correct Theme applied on contentView :smiley: 

Again, Thank you for this!

Btw: as there is no way to fix this within the module I'll close this.
