### ISSUE TITLE
Status bar is not semi-transparent, it rather has a black-color gradient from top and the color fades from black to the action bar color.

### ISSUE THREAD

**Issue by prashantsaini1** [manumaticx/Ti.DrawerLayout#71]
I tried the demo app you have added with this module and it seems that there is no way to remove the black color gradient at the top of the status bar. 

This gradient has black color and action bar color.

Please see the attached image and advise how to achieve the status bar exactly as you have displayed in the image at home page.

![screenshot_2016-08-02-00-43-26](https://cloud.githubusercontent.com/assets/20779626/17305881/8eb76132-584a-11e6-99c7-fb47abc651ac.png)

**Comment by manumaticx** [comment]
Hi,
is that android 4.x you are testing with?
See this image for the difference:
![](http://blog.raffaeu.com/wp-content/uploads/Android-and-the-transparent-status-bar_1146A/image_6.png)

**Comment by prashantsaini1** [comment]
No, it was Lollipop version 5.0.2 on two different devices - Samsung Galaxy On5 & Samsung Galaxy Core Prime.

But I just checked it on Moto E2 - Android version 5.1 and it is showing correctly.

![aa](https://cloud.githubusercontent.com/assets/20779626/17318609/2032cd5e-58a5-11e6-8a24-6444c11a8845.png)

If it is showing a gradient, then can we not make it look like the upper screenshot?

One last query -  will it show same drawer above status bar in this [Fokke Widget](https://github.com/FokkeZB/nl.fokkezb.drawer) ?

**Comment by manumaticx** [comment]
I'm afraid that this is a firmware related system behavior and you won't have any influence on that from within the module. At least I don't know how this could be achieved.

The Drawer Widget should not have any impact on the Drawer appearance itself. It's an API wrapper. If your Theme is set up correctly, everything should be fine.

**Comment by prashantsaini1** [comment]
Many thanks for your prompt replies.

I tested it deeply and found that Samsung Galaxy On5 (android 5.1.1) + Samsung Grand Prime (Android 5.0) devices both show a gradient kind of status bar..but Moto E2 (Android 5.1) device is showing it correctly. So, yes I believe that it is something related to firmware and still not sure why all google apps in my both samsung device are having the correct drawer over status bar.

And I also tried it using Drawer Widget and it works as expected and all we need is just to set the windowTranslucentStatus theme attribute to true.

**Comment by manumaticx** [comment]
I _thought_ it has to be something like a Samsung issue but if it does nor affect all of the Apps, maybe there is a solution for this. To be honest, I don't know and I actually have never seen this status bar gradient on my devices (Nexus) so I never had to think about it.

If you do find something please let me know. I'll close this issue for now.

**Comment by prashantsaini1** [comment]
I will try to find out the solution of this gradient as I came around some posts which shows how to do this on Samsung devices. I will surely update you here. Thanks
