### ISSUE TITLE
Memory leak caused by the Ti.DrawerLayout

### ISSUE THREAD

**Issue by asiby** [manumaticx/Ti.DrawerLayout#72]
Hi guys

Is it me? Or this module is causing major leak in windows? I have just noticed that the only way to avoid a leak is to not use the left view at all. No matter what we set the left view to, it will cause the entire window to stay retained.

I was just looking at the code in Drawer class and there this no way to set the leftView to null or to remove it before closing the window. And the code shows clearly that leftView cannot be set to null. Maybe we should allow setting it to null so that the module can remove the left view.

I am stuck very badly in ways that cannot be explained. In fact, the rest of my team has unfortunately started looking for an alternative. But I which it won't come to that.

Thought? Any suggestions are welcome? I like this module and I would like to keep it if this issue is confirmed and fixed. I can contribute code in the module if needed.

Thanks a lot.

**Comment by manumaticx** [comment]
Hi @asiby 

What Titanium Version are you using?

As discussed in #29 this bug was already researched. Can you confirm that the bugfix for [TIMOB-19891](https://jira.appcelerator.org/browse/TIMOB-19891) did not solve this issue? Otherwise, it might still be a bug in this drawer module.

Thanks for your report.

**Comment by asiby** [comment]
Thanks for answering.

I am using Titanium SDK 5.3.1 and some of my colleagues are using Ti SDK 5.4.0 with the same result.

I can confirm that if TIMOB-19891 is applied to the SDK we have (5.3.1 and 5.4.0), then we are still having a leak.

We have made some tests with simple windows containing no drawer and we couldn't notice any leak. But as soon as we use the drawer, we notice a leak. 

I went and added a destroy method to the drawer that will do the following ...

```
if (leftView != null){
	menu.removeView(getNativeView(leftView));
	leftView = null;
}

if (rightView != null){
	filter.removeView(getNativeView(rightView));
	rightView = null;
}

if (centerView != null){
	TiCompositeLayout fL = (TiCompositeLayout)layout.findViewById(id_content_frame);
	if (this.centerView != null) {
		if (fL != null) {
			fL.removeView(this.centerView.getOrCreateView().getNativeView());
			centerView = null;
		}
	}
}
```

That seemed to have done the trick for the leftView and the rightView. But the centerView still get stuck between the cracks.

We have even decided to attach views of larger sizes to the centerView and we can confirm that the size of the leak (when using the drawer) was proportional to the size of whatever that was in the drawer.

I am very desperate at this point and hoping for some miracle lol.

I have a screen capture of the Android Studio Monitoring tool showing the status of the memory at a given time. See the image here: https://ibin.co/2sozTyiWe01H.png

Thanks for any help.

Cheers

Ohh, cool. I have just discovered that I can also that the image file in this message box. Awesome.

![tidrawelayout_leak_2016_08_25_16_14_hprof_-_my_application_-____androidstudioprojects_myapplication_](https://cloud.githubusercontent.com/assets/455674/17985425/babf9c62-6ae3-11e6-9510-853ce13fde93.png)

**Comment by manumaticx** [comment]
@asiby Thanks for this awesome investigation.

Would you mind creating a pull request for this `destroy` method? 

In the meantime I'll have a look at the centerView trying to find what's leaking.

**Comment by asiby** [comment]
Sure. I will send it right after this message.

**Comment by asiby** [comment]
Please let me know if you need anything from me (additional testing, coding, etc.).

Thanks

**Comment by grazianogrespan** [comment]
Hi all!
I did some tests with android monitor and I can confirm this bug, on 5.4.0 GA with 1.4.2 module version, I would like to help you but I'm not so skilled in module development...hope will be fixed soon.

**Comment by manumaticx** [comment]
Sorry guys, I've just been a little busy these days. I'll try to finish the PR asap. Thanks a lot for your help! Really appreciate this. The bugfix will be released with the next minor version, hopefully I'll be able to push it this weekend.

**Comment by asiby** [comment]
Hi guys

Do you think that using `java.lang.ref.WeakReference` (and the related programming patterns) for the references to the left view, center view and right view might help?

I have never used it, but it seem to be a common practice in many Android libraries that I came across.

Cheers

**Comment by AndreaVitale** [comment]
I'm too interested on a fix for this, waiting for it! Thanks for your work guys!

**Comment by asiby** [comment]
I have also found that .setDrawerListener() is being used but .removeDrawerListener() is never called. That may be a thing to take a closer look at. I am writing all this while I am analyzing the code just in case someone else manages to fix it before me.

**Comment by AndreaVitale** [comment]
Any update about this issue? Thanks.
