### ISSUE TITLE
Titanium SDK 6.0.0 support?

### ISSUE THREAD

**Issue by Astrovic** [manumaticx/Ti.DrawerLayout#77]
Titanium 6.0.0 needed all native modules to be recompiled against the latest V8 version.

**Comment by NLKok** [comment]
+1

**Comment by mebarg** [comment]
yes we need a new build please

**Comment by grazianogrespan** [comment]
Hi all!  if anyone needs a recompiled version of the module I can drop it here. 
If you have other modules to recompile with 6.0.0 GA you could just follow this guide, it is very easy.
[http://skypanther.com/2016/10/rebuilding-modules-for-titanium-6/](url)

[com.tripvi.drawerlayout-android-2.4.2.zip](https://github.com/manumaticx/Ti.DrawerLayout/files/599707/com.tripvi.drawerlayout-android-2.4.2.zip)
