### ISSUE TITLE
Drawer in all activities in application

### ISSUE THREAD

**Issue by granit1986** [manumaticx/Ti.DrawerLayout#8]
Hello.
I have >10 windows and trying add drawer in they all.
How I can do that?

**Comment by manumaticx** [comment]
@granit1986 Hi. As stated [here](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App#limitations) there isn't a really smart way of achieving this, for now. I'll think about another solution.

**Comment by deckameron** [comment]
@granit1986,

You could use [this module](https://github.com/nborracha/com.yallaya.fragments) and change the fragment on the centerView.

**Comment by manumaticx** [comment]
@deckameron There is actually no need to use another module to replace the centerView as you can just replace it with `drawer.replaceCenterView();` but this does not solve to problem making the drawer accessible from other activities.

I'll definitely look at this again when I prepare the module for Material theme and the new titanium sdk.

**Comment by granit1986** [comment]
Now i'am create new drawer for each activity and it form fine

**Comment by falkolab** [comment]
@granit1986 Have you checked the leaked memory after repeated opening and closing of the activity with drawer? https://github.com/manumaticx/Ti.DrawerLayout/issues/29

**Comment by manumaticx** [comment]
I'm afraid we cannot achieve this from the module itself. That needs no be implemented in the parent activity. There's probably a way to do this in Titanium. E.g. you could create your custom window that adds your drawer instance by default or something like this.

But as I can't fix it here, I'll close this issue now.
