### ISSUE TITLE
How to use with alloy?

### ISSUE THREAD

**Issue by ikalangita** [manumaticx/Ti.DrawerLayout#80]
Hello,

Is it possible to specify leftView and rightView directly form alloy?, doing this the left view not appearing.

`
var leftView = $.leftView;//Ti.UI.createView({backgroundColor:'gray'}); `
`var centerView = $.rightView;//Ti.UI.createView({backgroundColor:'white'});`

Thanks

**Comment by HazemKhaled** [comment]
use this widget for 1 code with iOS and Android
https://github.com/fokkezb/nl.fokkezb.drawer
