### ISSUE TITLE
the 'com.tripvi.drawerlayout' module is not supported by titanium sdk 6.0.2 GA

### ISSUE THREAD

**Issue by ManasMack** [manumaticx/Ti.DrawerLayout#81]
getting the 'com.tripvi.drawerlayout' module is not supported by titanium sdk 6.0.2 GA error message in tiapp.xml file even if modules latest verions 2.0.0 is added.

**Comment by manumaticx** [comment]
Since this should be solved in #78 maybe @HazemKhaled can help here?

@ManasMack Are you sure the project builds with the updated module and there is no older version (locally or globally) installed that mistakenly gets packaged?

**Comment by R4mpancy** [comment]
Not sure if I experienced the same problem, but with a different Ti SDK. Any SDK I specified was showing up as not supported. My error was that when loading the module into my project I was loading the master zip file, not the version specific zip in the master's dist folder. Could be the same issue ManasMack is experiencing. 
The module works great though and I'm very happy with it!

**Comment by drauggres** [comment]
Support 7.0.0 now
