### ISSUE TITLE
Make Actionbar supporting RTL

### ISSUE THREAD

**Issue by AhmedMohamed2014** [manumaticx/Ti.DrawerLayout#85]
please can you make actionbar supporting RTL to put hamburger menu icon and title on right side.

**Comment by manumaticx** [comment]
It should work if you use this in you manifest:

```
<application
    android:supportsRtl="true">
</application>
```

Doesn't it?

**Comment by AhmedMohamed2014** [comment]
Thanks manumaticx it's worked

**Comment by manumaticx** [comment]
Perfect :)

**Comment by HazemKhaled** [comment]
@AhmedMohamed2014 this can help
https://github.com/HazemKhaled/Titanium_RTL_guide
