### ISSUE TITLE
libstlport_shared.so not found

### ISSUE THREAD

**Issue by caspahouzer** [manumaticx/Ti.DrawerLayout#86]
Hi, I got this error in every SDK since 6.0.0.GA

What can I do??

> [ERROR] :  TiApplication: (main) [11,424] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dlopen failed: library "libstlport_shared.so" not found; Titanium 6.2.2,2017/09/19 16:01,undefined
> [ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: library "libstlport_shared.so" not found
> [ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
> [ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:1076)
> [ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
> [ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
> [ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
> [ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
> [ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
> [ERROR] :  TiApplication: 	at com.lightapps.flandroid.FlandroidApplication.onCreate(FlandroidApplication.java:49)
> [ERROR] :  TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
> [ERROR] :  TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
> [ERROR] :  TiApplication: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
> [ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
> [ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> [ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:148)
> [ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
> [ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
> [ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> [ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by caspahouzer** [comment]
Sorry, fails with an other module not ready for 6.0.0

**Comment by GenesisSelf** [comment]
Did you find a solution?
