### ISSUE TITLE
Webview issues

### ISSUE THREAD

**Issue by manumaticx** [manumaticx/Ti.DrawerLayout#9]
It seems there are problems with WebViews:
https://github.com/Tripvi/Ti.DrawerLayout/issues/48

Probably another Fragment-related issue.

**Comment by AppWerft** [comment]
The same problem with mapviews. I added a mapview into the contentView  of drawer and the views keeps empty.
https://gist.github.com/AppWerft/73129b6ca56a788f00a6

**Comment by manumaticx** [comment]
@AppWerft known issue #4 - this is ti.map bug

**Comment by manumaticx** [comment]
Not seeing any issue here anymore. As expected this is fixed by wiping out the content fragment.
